# action.yml
name: 'AddRemoveLabel'
description: 'Manage labels on GH pull requests'
inputs:
  token:
    description: 'GH token'
    required: true
  add_label:
    description: 'Label to add'
    required: false
  remove_label:
    description: 'Label to remove'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.add_label }}
    - ${{ inputs.remove_label }}
