# action.yml
name: 'AddRemoveLabel'
description: 'Manage labels on GH pull requests'
inputs:
  GITHUB_TOKEN:
    description: 'GH token'
    required: true
  GITHUB_EVENT_PATH:
    description: 'GH event path'
    required: true
  ADD_LABEL:
    description: 'Label to add'
    required: false
  REMOVE_LABEL:
    description: 'Label to remove'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.GITHUB_EVENT_PATH }}
    - ${{ inputs.ADD_LABEL }}
    - ${{ inputs.REMOVE_LABEL }}
